export const THEME = {
  colorGray50: 'oklch(0.985 0.002 247.839)',
  colorGray100: 'oklch(0.967 0.003 264.542)',
  colorGray200: 'oklch(0.928 0.006 264.531)',
  colorGray300: 'oklch(0.872 0.01 258.338)',
  colorGray400: 'oklch(0.707 0.022 261.325)',
  colorGray500: 'oklch(0.551 0.027 264.364)',
  colorGray600: 'oklch(0.446 0.03 256.802)',
  colorGray700: 'oklch(0.373 0.034 259.733)',
  colorGray800: 'oklch(0.278 0.033 256.848)',
  colorGray900: 'oklch(0.21 0.034 264.665)',
  colorGray950: 'oklch(0.13 0.028 261.692)',
} as const;

export const GLOBAL_STYLES = {
  root: {
    backgroundColor: THEME.colorGray200,
    transition: 'opacity 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
    border: '2px solid black',
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    left: '64px',
    opacity: 0,
    overflow: 'hidden',
    padding: '3px',
    pointerEvents: 'none',
    position: 'fixed',
    top: '8px',
  },
  actionContainer: {
    alignItems: 'center',
    display: 'flex',
    width: '100%',
  },
  mainContent: {
    alignItems: 'center',
    display: 'flex',
    height: '50vh',
    flexDirection: 'column',
    justifyContent: 'center',
    width: 'max(37.5vw, 480px)',
  },
  tabContainer: {
    alignItems: 'end',
    display: 'flex',
    justifyContent: 'start',
    flexDirection: 'row',
    marginTop: '3px',
    overflowX: 'auto',
    width: '100%',
  },
  tab: {
    border: '2px solid black',
    borderBottom: 'none',
    borderRadius: '5px 5px 0 0',
  },
  windowContainer: {
    display: 'flex',
    height: '100%',
    flexDirection: 'column',
    width: '100%',
  },
  windowHead: {
    alignItems: 'center',
    backgroundColor: THEME.colorGray100,
    border: '2px solid black',
    borderBottom: 'none',
    display: 'flex',
    flex: 1,
    justifyContent: 'start',
    padding: '10px',
  },
  windowBody: {
    backgroundColor: THEME.colorGray200,
    border: '2px solid black',
    display: 'flex',
    flex: 10,
    flexDirection: 'column',
  },
  triggerContainer: {
    alignItems: 'start',
    backgroundColor: THEME.colorGray100,
    borderBottom: '2px solid black',
    boxShadow: '0px 4px 8px -4px #000',
    display: 'flex',
    flexDirection: 'column',
    padding: '10px',
    position: 'relative',
  },
  triggerActionContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    direction: 'ltr',
    justifyContent: 'space-between',
    position: 'absolute',
    right: '0px',
  },
  triggerRowContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  triggerPropContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'start',
    marginBottom: '5px',
    width: '100%',
    whiteSpace: 'nowrap',
  },
  spacedProperty: {
    margin: '0 5px',
  },
  newTriggerButton: {
    backgroundColor: THEME.colorGray50,
    border: '2px solid black',
    borderRadius: '50%',
    bottom: '0px',
    boxShadow: '0px 2px 8px 0px #000',
    left: '0px',
    marginLeft: 'auto',
    marginRight: 'auto',
    position: 'absolute',
    right: '0px',
    transform: 'translateY(50%)',
    zIndex: 1,
  },
} satisfies Record<string, React.CSSProperties>;
